[package]
name = "BrowserLoginsDump"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-next = "2.0.0"
rusqlite = "0.34.0"
serde = {version= "1.0.219", features=["derive"]}
serde_json = "1.0.140"
